/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library 
{
	public static void main(String args[])
	{
		System.out.println("when there is a fire, commit and push");
	}
	public boolean someLibraryMethod() 
	{
		return true;
	}
}

